const BRAND_COLOR = '#57C69E' as const

const LIGHT_THEME_BACKGROUND = '#EEEEEE' as const
const LIGHT_THEME_TEXT = '#111111' as const
const LIGHT_THEME_VARIANT = '#333333' as const
const LIGHT_THEME_SECONDARY = '#777777' as const
const LIGHT_THEME_SECONDARY_VARIANT = '#BBBBBB' as const
const LIGHT_THEME_BACKGROUND_VARIANT = '#CCCCCC' as const

const DARK_THEME_BACKGROUND = '#111111' as const
const DARK_THEME_TEXT = '#EEEEEE' as const
const DARK_THEME_VARIANT = '#CCCCCC' as const
const DARK_THEME_SECONDARY = '#888888' as const
const DARK_THEME_SECONDARY_VARIANT = '#444444' as const
const DARK_THEME_BACKGROUND_VARIANT = '#333333' as const

const SUCCESS = '#2eab4f' as const
const WARNING = '#e39e24' as const
const ERROR = '#d12e11' as const

export {
  BRAND_COLOR,
  LIGHT_THEME_BACKGROUND,
  LIGHT_THEME_TEXT,
  LIGHT_THEME_VARIANT,
  LIGHT_THEME_SECONDARY,
  LIGHT_THEME_SECONDARY_VARIANT,
  LIGHT_THEME_BACKGROUND_VARIANT,
  DARK_THEME_BACKGROUND,
  DARK_THEME_TEXT,
  DARK_THEME_VARIANT,
  DARK_THEME_SECONDARY,
  DARK_THEME_SECONDARY_VARIANT,
  DARK_THEME_BACKGROUND_VARIANT,
  SUCCESS,
  WARNING,
  ERROR
}
